#!/usr/bin/bash
if [ ! -d bin ]; then
	mkdir bin
fi
EXE=bin/genetic.exe
g++ genetic.cpp -O3 -o $EXE
if [ $1 ]; then
	echo "Executando a instância \"$1\"."
	 ./$EXE < $1
else
	output="random_instances/results_genetic"
	echo "Executando as intâncias em random_intances."
	echo $(date) > $output
	for i in $(seq 7 12); do
		for j in $(seq 1 5); do
			results=$(./$EXE < random_instances/${i}_${j})
			echo "${i}_${j}: ${result}"
			echo "${i}_${j}: ${result}" >> $output
		done;
	done;
fi
rm $EXE
