#!/usr/bin/bash
if [ ! -d bin ]; then
	mkdir bin
fi
EXE=bin/genetic.exe
g++ genetic.cpp -O3 -o $EXE
if [ $1 ]; then
	echo "Executando a instância \"$1\"."
	 ./$EXE < $1
else
	output="random_instances/results_genetic"
	echo "Executando as intâncias em random_intances."
	echo $(date) > $output
	for i in 5 6 7 8; do
		for j in 1 2 3 4 5; do
			results=$(./$EXE < random_instances/${i}_${j})
			echo "${j}_${i}: ${result}"
			echo "${j}_${i}: ${result}" >> $output
		done;
	done;
fi
rm $EXE
