#!/usr/bin/bash
g++ genetic.cpp -O3 -o bin
if [ $1 ]; then
	echo "Executando a instância \"$1\"."
	 ./bin < $1
else
	echo "Executando as intâncias em "
	output="random_instances/results_genetic"
	echo $(date) > $output
	for i in 4 5 6 7 8; do
		for j in 1 2 3 4 5; do
			./bin < random_instances/${i}_${j} >> $output 
		done;
	done;
fi
rm bin
