#!/usr/bin/bash
if [ ! -d bin ]; then 
	mkdir bin
fi
EXE=bin/brute_force.exe
g++ brute_force.cpp -O3 -o $EXE
if [ $1 ]; then
	echo "Executando a instância \"$1\"."
	./$EXE < $1
else 
	output=random_instances/results
	echo "Executando todos as instâncias em random_instances."
	echo $(date) > $output
	for i in $(seq 7 12); do 
	    for j in $(seq 1 5); do 
		result=$(./$EXE < "random_instances/${i}_${j}")
		echo "${i}_${j}: ${result}"
		echo "${i}_${j}: ${result}" >> $output 
	    done 
	done
fi
